/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alliteration;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void correctAlliterations() {
        Main app = new Main();
		String[] lines = {"He has four fanatic fantastic fans",
						  "There may be no alliteration in a sequence",
						  "Round the rugged rock the ragged rascal ran",
						  "area artic Soul Silly subway ant artic none"};
		int[] expected = {2, 0, 2, 3};
		int i = 0;
		for(String line: lines) {
			int alliterations = app.getAlliterations(line);
			String msgError = "Error al calcular aliteraciones en: " + line;
			assertEquals(expected[i], alliterations, msgError);
			i++;
		}
    }
}
